version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/openjdk:${OPENJDK_TAG}-${OPENJDK_VERSION}"
    container_name: "${APP_NAME}"
    command: tail -f /dev/null
    volumes:
      #- "./${CODE_PATH}:${APP_CODE_PATH}"
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8082:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

  # =db
  db:
    image: "sindriainc/mariadb:${MARIADB_TAG}-${MARIADB_VERSION}"
    container_name: "${APP_NAME}-db"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      #- "${APP_DATA_PATH}/db/:/var/lib/mysql:delegated"
      - "/var/lib/mysql"
    hostname: "${APP_NAME}-db.local"
    #ports:
    #  - "3306:3306"
    networks:
      default:
        ipv4_address: "${DB_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}-db.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${DB_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}-db.local"

# =networks
networks:
  default:
    name: "vpc_xp-web"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_xdev:
#    external: true
