version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/openjdk:${OPENJDK_TAG}-${OPENJDK_VERSION}"
    container_name: "${APP_NAME}"
    command: tail -f /dev/null
    volumes:
      #- "./${CODE_PATH}:${APP_CODE_PATH}"
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8082:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_app_name:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"
  # =db
  db:
    image: "postgres:11"
    container_name: "${APP_NAME}-db"
    environment:
      - POSTGRES_PASSWORD=${APP_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${APP_DB_DATABASE}
      - POSTGRES_USER=${APP_DB_USERNAME}
    volumes:
      - "db:/var/lib/postgresql/data"
    hostname: "${APP_NAME}-db.local"
    #ports:
    #  - "5432:5432"
    networks:
      default:
        ipv4_address: "${APP_DB_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}-db.local"

# =networks
networks:
  default:
    name: "vpc_xp-web"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_app_name:
#    external: true

# =volumes
volumes:
  db:
